"""initial migration

Revision ID: cc18c6281c76
Revises: 
Create Date: 2020-11-13 12:54:01.507097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc18c6281c76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('email', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'password')
    op.drop_column('users', 'name')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=64), nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'roles', ['role_id'], ['idx'])
    op.create_index('ix_users_name', 'users', ['name'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
