# Generated by Django 3.1.2 on 2020-11-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('birthday', models.DateField()),
                ('gender', models.BooleanField()),
            ],
        ),
    ]
