# Generated by Django 3.1.2 on 2020-11-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_day', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favor_item', models.CharField(max_length=20)),
                ('item_type', models.CharField(max_length=10)),
                ('how_long', models.IntegerField()),
                ('whos_favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second_day.selfintroduction')),
            ],
        ),
    ]
