# Generated by Django 3.1.2 on 2020-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_day', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfintroduction',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='selfintroduction',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selfintroduction',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='selfintroduction',
            name='gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='selfintroduction',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
