# Generated by Django 3.1.2 on 2020-11-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_day', '0003_auto_20201105_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favor_item',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='how_long',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='item_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
